# Generated by Django 5.2.7 on 2025-11-07 06:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_alter_card_options_alter_deck_options_deck_deck_type'),
        ('scheduler', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulingdata',
            old_name='ease',
            new_name='ease_factor',
        ),
        migrations.AlterField(
            model_name='schedulingdata',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='schedulingdata',
            unique_together={('user', 'card')},
        ),
    ]
