# Generated by Django 5.2.7 on 2025-10-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('zh', 'Chino'), ('ja', 'Japonés'), ('ru', 'Ruso'), ('ar', 'Árabe')], default='en', max_length=20),
        ),
    ]
