# Generated by Django 5.2.7 on 2025-11-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['deck', 'id']},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['title'], 'verbose_name': 'Deck', 'verbose_name_plural': 'Decks'},
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_type',
            field=models.CharField(choices=[('basic', 'Básica'), ('cloze', 'Cloze'), ('image', 'Imagen'), ('audio', 'Audio')], default='basic', max_length=20),
        ),
    ]
