# Generated by Django 5.2.7 on 2025-10-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonclass',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_classes', to='decks.deck'),
        ),
        migrations.AddField(
            model_name='userclassprogress',
            name='lesson_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lessonclass'),
        ),
    ]
